### ISSUE TITLE
Sprint 0 crear readme.md 

### ISSUE THREAD

**Issue by profeale** [profeale/PBKaula15#1]
Extraer del material de Scrum los siguientes conceptos: Ceremonias, Artefactos y Roles.
Registrar estos conceptos dentro del readme.md y renombrarlo como ConceptosScrum.md

**Comment by cndlucero** [comment]
CEREMONIAS

● Sprint Planning Meeting (reunión de planificación del sprint). Se produce al iniciar cada Sprint y tiene por objetivo decidir que se va a realizar en el Sprint.
● Daily Scrum Meeting (reunión periódica). Se produce diariamente, y tiene un máximo de 20 min. de duración. Tiene por objeto tratar qué es lo que se hizo, qué se va a hacer y qué problemas se han encontrado, esto a fines de encontrar soluciones en la diaria.
● Sprint Review Meeting (reunión de revisión del Sprint). Se produce al finalizar el Sprint y tiene por objeto mostrar qué es lo que se ha completado y qué no. Debe estar presente el Product Owner
● Sprint Retrospective Meeting (reunión de retrospectiva del Sprint). Se produce también al finalizar el Sprint y tiene por objeto documentar qué ha funcionado y qué no ha funcionado en el Sprint. La idea de dicha reunión es centrar al equipo en lo que salió bien y en lo que debe mejorar para la próxima iteración. De ninguna manera se centra en lo que salió mal.

ROLES
1. Roles centrales
Los roles centrales son aquellos que su participación es indispensable para la realización del proyecto, están comprometidos con el proyecto y son responsables del éxito de cada sprint y del proyecto en general. Estos son:
Product owner
Scrum master
Equipo Scrum
2. Roles no centrales
Los roles no centrales son aquellos cuya participación en el proyecto es importante pero no depende de ellos el éxito o fracaso del proyecto, es importante siempre identificar los individuos de esta categoría y mantenerlos siempre presentes, en cualquier momento su rol puede ser decisivo para el proyecto (por ejemplo si es un sponsor). Estos son:
Stakeholders
Cliente
Usuarios
Patrocinador (sponsor)
Vendedores
Scrum Guidance Body


¿Qué son los Artefactos de Scrum?

Los Artefactos según la guía Scrum, están diseñados para maximizar la transparencia de la información, que es necesaria para asegurar que todo el equipo tenga el mismo entendimiento del Artefacto.
Las decisiones para optimizar el valor y controlar el riesgo se hacen con base en estos Artefactos, por lo tanto si no son lo suficientemente transparentes se puede incurrir en decisiones erróneas.
Pero veamos cuales son estos Artefactos:
Product Backlog
Es una lista ordenada, que contiene todo lo que podría ser necesario en el producto y es la única fuente de requisitos para hacer cambios en el producto.
El único responsable del Product Backlog es el Product Owner. Es el encargado de ordenar y añadir ítems.
Por definición, esta lista nunca está completa, sino que es un ente vivo y dinámico, que va cambiando según lo hace el entorno y el propio producto para ser adecuado, competitivo y útil.
Los ítems que aparecen en el Product Backlog tienen los siguientes atributos:
Descripción
Ordenación
Estimación
Valor
A medida que el producto va siendo usado y se recibe feedback, la lista se va haciendo más larga y detallada.
Los elementos o ítems que están ordenados más arriba, normalmente son los más detallados y claros, ya que serán los más próximos a ser desarrollados.
Sprint Backlog
Son los ítems o elementos del Product Backlog seleccionados para ser ejecutados durante el Sprint en curso. Así pues, el Sprint Backlog es un plan para entregar un Incremento de producto “Terminado” al final del Sprint.
A medida que se va trabajando sobre el producto, va apareciendo nuevo trabajo, que el Equipo de Desarrollo va añadiendo al Sprint Backlog.
El Sprint Backlog solo lo puede modificar durante el Sprint, el Equipo de Desarrollo, así como eliminarlo.
Incremento

Es la suma de todos los elementos del Sprint Backlog “Terminados” más los Incrementos de Sprints anteriores.
“Terminado” significa que puede ser utilizado y que además cumple con la “Definición de Terminado”, es decir, lo que todo el mundo entiende dentro del equipo por terminado.
